/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package demofinal;
import java.util.Vector;
import Business.DangNhap;
import connection.DBhelper;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class frmViews extends javax.swing.JFrame {
     private Statement st=null;
     private ResultSet rs=null;
     private Vector vColum=new Vector();
     private Vector vData =new Vector();
 
    public frmViews() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        tf_user = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        btn_check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        a.setText("user");

        b.setText("pass");

        btn_check.setText("check");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btn_them)
                        .addGap(45, 45, 45)
                        .addComponent(btn_xoa)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(a)
                        .addGap(18, 18, 18)
                        .addComponent(tf_user)
                        .addGap(18, 18, 18)
                        .addComponent(b)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_thoat)
                        .addGap(41, 41, 41)
                        .addComponent(btn_check)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a)
                    .addComponent(b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thoat)
                    .addComponent(btn_xoa)
                    .addComponent(btn_them)
                    .addComponent(btn_check))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        
        String u=tf_user.getText();
        String p=tf_pass.getText();
        themUser(u,p);
        clearTable(table);
        showTableDangNhap();
        
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        String u=tf_user.getText();
        xoaUser(u);
        clearTable(table);
        showTableDangNhap();
    }//GEN-LAST:event_btn_xoaActionPerformed

    //kiem tra trong co so du lieu co tai khoan nay khong;
    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        // TODO add your handling code here:
         DBhelper db=new DBhelper();
         int e=0;
        try {
            db.connect();
            st=db.conn.createStatement();
            String sql= "select * from thongtintaikhoan where username= N'"+tf_user.getText()+"' and password =N'"+tf_pass.getText()+"' ";
            rs=st.executeQuery(sql); 
           if(rs!=null){
            if(rs.next()){
                
               // if (rs.getString("username").equals(new String(tf_user.getText()))) {
                JOptionPane.showMessageDialog(this,"nick co ton tai");     
              //  }
                         
            }else{
                JOptionPane.showMessageDialog(this,"nick ko ton tai");
            }
                   
          }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       frmViews view=new frmViews();
       view.showTableDangNhap();
   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables

    
     public void showTableDangNhap() {
         DBhelper db=new DBhelper();
        try {
            db.connect();
            
              try {
                st=db.conn.createStatement();
                String sql="select * from thongtintaikhoan";
                rs=st.executeQuery(sql);
                ResultSetMetaData rsmt =rs.getMetaData();
                for(int i=1;i<=rsmt.getColumnCount();i++){
                vColum.add(rsmt.getColumnName(i));
                }
                 while (rs.next())
                {
                Vector vRow =new Vector();
                for(int i=1;i<=rsmt.getColumnCount();i++){
                    vRow.add(rs.getString(i));
                }
                
                vData.add(vRow);
                table.setModel(new DefaultTableModel(vData,vColum));
                }
            
             } catch (SQLException ex) {
            ex.printStackTrace();
            }    
            finally{
            try {
                rs.close();
                st.close();
                db.conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
              }
            
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(frmViews.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       
        
    }

     
    public void xoaUser(String u) throws HeadlessException {
        // TODO add your handling code here:
        DBhelper db=new DBhelper();
           try {
             db.connect();
         } catch (SQLException ex) {
             ex.printStackTrace();
         }
         
          String username=tf_user.getText();
          String password=tf_pass.getText();
          if(!username.equals("")){             
          try {
               st=db.conn.createStatement();
               String sql="delete thongtintaikhoan where username='"+ u+ "' ";
               JOptionPane.showMessageDialog(this,"da xoa tai khoan nay");
               rs=st.executeQuery(sql);
           } catch (SQLException ex) {
               ex.printStackTrace();
           }
            finally{
            try {
                rs.close();
                st.close();
                db.conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
           } 
        }//end if
          else{
              JOptionPane.showMessageDialog(this,"ban da de trong ja tri can nhap");
          }
    }

    
    public void themUser(String u,String p) throws HeadlessException {
        // TODO add your handling code here:
        DBhelper db=new DBhelper();
          try {
            db.connect();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
         String username=u;
         String password=p;
         if((!username.equals(""))&(!password.equals(""))){             
         try {
              st=db.conn.createStatement();
              String sql="insert into thongtintaikhoan(username,password) values('"+username+"','"+password+"') ";
              JOptionPane.showMessageDialog(this,"da them tai khoan nay");
              rs=st.executeQuery(sql);
          } catch (SQLException ex) {
              ex.printStackTrace();
          }
           finally{
           try {
               rs.close();
               st.close();
               db.conn.close();
           } catch (SQLException ex) {
               ex.printStackTrace();
           }
           
          } 
       }//end if
         else{
             JOptionPane.showMessageDialog(this,"ban da de trong ja tri can nhap");
         }
    }
    
    
  public  void clearTable(JTable table) {
   
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
   }  
    
}   
    
    
    

